### ISSUE TITLE
Should payment instrument details be included at registration?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#12]
Migrated from https://github.com/w3c/webpayments/issues/142

@ianbjacobs said:

I wouldn't call these "payment instruments" but I support the idea of apps being able to register multiple "choices" for the user that reflect different combinations of payment method identifiers.

Apps can use this to reflect the instruments that the user has installed or just to put the choice of payment method or funding source in the initial app selection list.

See also: https://github.com/w3c/browser-payment-api/issues/185#issuecomment-223047965

@adrianhopebailie said:

The latest payment apps proposal includes the idea of "payment options" which supports this requirement.

A payment app (single endpoint URL) can register multiple payment options (groups of supported payment methods, a single label and icon for user selection).

**Comment by ianbjacobs** [comment]
@rsolomakhin has <a href="https://github.com/w3c/webpayments-payment-apps-api/issues/34#issue-175595397">weighed in</a> on this question: " I have heard feedback that this may not be desirable for the first iteration of the payment app spec, because it's one more layer of abstraction with marginal benefit. Let's stick with one-to-one mapping here for now. So BobPay should be able to display only one item on browser UI: "BobPay"."

**Comment by ianbjacobs** [comment]
As of the 30 November call I believe there was consensus to include options; see this edit to resolve this issue:
 https://github.com/w3c/webpayments-payment-apps-api/pull/70/commits/0176dfb5ee84c087109149d024989d83eefd1cf3
