### ISSUE TITLE
Origin should include iframe(s)

### ISSUE THREAD

**Issue by frank-hoffmann** [w3c/webpayments-payment-apps-api#120]
If the Payment Request is initiated from within an iframe on the merchant page it is of interest for the Payment App to receive the iframe origin as well as the containing page (merchant) origin.

**Suggested change:**
* The origin field in the PaymentAppRequest is an array instead of a string
* The value of origin is a list of all the origins involved in the PaymetRequest invocation.

**Example:**
```
origin: ["https://www.merchantsite.com", "https://pspiframe.com", "https://www.pspcarddetailsiframe.com"]
```
*I have no preference whether the list should be in the above order or reversed*

**Comment by rsolomakhin** [comment]
Let's pass in only the `origin` and the `iframeOrigin` instead. The top-level `origin` is useful because that's what user sees in the address bar of the user agent. The `iframeOrigin` of the iframe that invoked `PaymentRequest` is useful for the payment app to filter out origins that are not allowed to invoke them. (For example, let's suppose `https://bobpay.com` provides an iframe for their 100,000 merchants. The payment app could filter on `"iframeOrigin": "https://bobpay.com"` and not keep track of the full list of 100,000 merchant origins in their client-side code.) I don't see a point in passing in the full list of iframe origins to the payment app.

**Comment by marcoscaceres** [comment]
We probably want some generic way of saying "iframe" without binding the name to a HTML element tho.

**Comment by frank-hoffmann** [comment]
The argument for having an array instead is that you might have nested iframes, e.g. PSPs. Then Payment Apps might be interested of matching on the "container" iframe rather then the one initiating the Payment Request. This would be hard to cater for if we specify `origin` and `iframeOrigin` without breaking the API. I do not see this as a must but I think it is more future proof and we give the Payment App as much context as possible

**Comment by rsolomakhin** [comment]
@frank-hoffmann The payment app developers that interact with us only mention the iframe that calls the `new PaymentRequest()`. Future proofing is something that I tend to oppose, because it leads to unused bloat. If there's a better argument or use case for providing the origins of the middle frames, please let me know.

**Comment by frank-hoffmann** [comment]
@rsolomakhin Lets check with the PSP members in the group to see how common it is that they use nested iframes and if so how they are structured

**Comment by dlongley** [comment]
@marcoscaceres,

> We probably want some generic way of saying "iframe" without binding the name to a HTML element tho.

I think what you want, semantically, is the origin of the invoker -- so maybe something along the lines of `invokingOrigin` or `sourceOrigin`.

**Comment by frank-hoffmann** [comment]
@rsolomakhin I checked wth the PSPs we are working with and it seems like nested iframe is an uncommon practice so I am fine with your suggestion. Thanks

**Comment by rsolomakhin** [comment]
The task force has resolved to use `topLevelOrigin` and `paymentRequestOrigin` to better differentiate the two.

**Comment by ianbjacobs** [comment]
Pull request for this:
 https://github.com/w3c/webpayments-payment-apps-api/pull/130

**Comment by ianbjacobs** [comment]
Closed with:
 https://github.com/w3c/webpayments-payment-apps-api/commit/f8fc689bf08283e47002468242bec7af1c0cc753
