### ISSUE TITLE
Do we need "Payment Manager" and "Payment Handler"?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#127]
@mattsaxon originally brought this to my attention. The specification is called "Payment Handler API" but the object that we create to handle payment requests is called PaymentManager. I had a discussion with @adamroach about this and our sense is that we don't both terms.

PROPOSED: Remove the phrase Payment Manager from the spec, renaming the "PaymentManager" interface the "PaymentHandler" interface.

Ian

**Comment by rsolomakhin** [comment]
:+1:

**Comment by adrianhopebailie** [comment]
👎  - these are very different things

A **Payment Handler** is a piece of code that _handles_ a [PaymentRequestEvent](https://w3c.github.io/webpayments-payment-apps-api/#dom-paymentrequestevent). This specification defines an extension to `ServiceWorkerGlobalScope` adding the event handler `onpaymentrequest` where developers can attach payment handlers.

On the other hand, a **Payment Manager** is an extension to `ServiceWorkerRegistration` and is the place where developers define the capabilities of their payment app through addition of instruments to the payment manager.

A developer could install a service worker that has a payment handler and not register any capabilities but the result would be that the handler would never be invoked.

When a user selects an instrument the `onpaymentrequest` event handler on the Service Worker from which that instrument was registered is invoked and the event object contains the instrument identifier allowing the handler to determine which instrument the user selected.

**Comment by mattsaxon** [comment]
So if a Payment Handler is a synonym for EventHandler  onpaymentequest, should the spec be called just "Payment Handler", since it is so much more. Also, what was the original rationale for changing away from Payment App, especially since the specification still refer to Payment Apps (e.g. PaymentAppRequest).

Even though I see the point @adrianhopebailie makes above, the existence of the separate terms of Payment App, Payment Handler and Payment Manager is confusing. Perhaps clearing up the Payment App terminology may be a good 1st step to removing that confusion.

My feeling (without the context and history) is;

1. Spec should be called Web Payment App
2. Payment Handler is a synonym for "EventHandler onpaymentrequest" and we should perhaps call that out fairly early in the spec. However I am unconvinced that we need the term Payment Handler very often in the spec, instead using the term Payment App
3. PaymentAppResponse & PaymentAppRequest make sense given point 1
4. Payment Manager would remain

**Comment by adrianhopebailie** [comment]
Resolved to close on TF call today.
https://www.w3.org/2017/04/18-apps-minutes.html#item03

@mattsaxon will do another review of the text before we go to FPWD and log new issues if he finds any where the terminology is unclear.

**Comment by mattsaxon** [comment]
PaymentAppRequest and PaymentAppResponse should be renamed to PaymentHandler... IMO.

Doing this will nicely keep the concept of the Payment App a purely logical construct.

Ps. I like the new diagram, it works very well

**Comment by adrianhopebailie** [comment]
@mattsaxon Suggest we close in favour of #142?

**Comment by mattsaxon** [comment]
Close to a dupicate, but to be picky other issue doesn't reference paymentapprequest.

**Comment by adrianhopebailie** [comment]
> other issue doesn't reference paymentapprequest.

It proposes to replace it

**Comment by mattsaxon** [comment]
Ok
