### ISSUE TITLE
Merge PaymentAppResponse and PaymentRequestEvent

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-payment-apps-api#142]
I see no reason to have both of these. 
The PaymentRequestEvent should be updated to look like this:

```
interface PaymentRequestEvent : ExtendableEvent {
    readonly attribute DOMString topLevelOrigin;
    readonly attribute DOMString paymentRequestOrigin;
    readonly attribute DOMString paymentRequestId;
    readonly attribute FrozenArray<PaymentMethodData> methodData;
    readonly attribute PaymentItem total;
    readonly attribute FrozenArray<PaymentDetailsModifier> modifiers;
    readonly attribute DOMString instrumentId;
    Promise<WindowClient> openWindow(USVString url);
    void respondWith(Promise<PaymentHandlerResponse> response);
};
```
And `PaymentAppResponse` should be renamed to `PaymentHandlerResponse`.

This would also address @mattsaxon 's comments on #127

**Comment by ianbjacobs** [comment]
The proposal seems reasonable and at least for now I don't see any reason to keep them separate, since all that happens to aPaymentAppRequest is that it is handed to a handler. 

The 7.5 Handling a PaymentRequestEvent algorithm will need to be updated.

+1 to a PR from you on this, or if you want I can take a stab.

Ian

**Comment by ianbjacobs** [comment]
This has been done in the latest draft.
