### ISSUE TITLE
Missing question mark,

### ISSUE THREAD

**Issue by gogerald** [w3c/webpayments-payment-apps-api#163]
is 
```
[Exposed=ServiceWorker]
interface PaymentRequestEvent : ExtendableEvent {
    ...
    Promise<WindowClient> openWindow(USVString url);
   ...
};
```
should be
```
[Exposed=ServiceWorker]
interface PaymentRequestEvent : ExtendableEvent {
    ...
    Promise<WindowClient?> openWindow(USVString url);
   ...
};
```
to allow return null

**Comment by romandev** [comment]
According to the OpenWindow Algorithm 8-4, unlike clients.openWindow(), this function will create controlled window client only.
So, it will always be non-null?

[1] https://w3c.github.io/payment-handler/#dfn-open-window-algorithm

**Comment by rsolomakhin** [comment]
@romandev : What does the word "controlled" mean in this context?

@gogerald : In what circumstances would `openWindow()` return a null?

**Comment by gogerald** [comment]
The OpenWindow Algorithm 8-6 checks "If event.[[windowClient]] is not null", does that mean it could be null?

Right now, I can think of the situation is that, the user clicks 'pay' button, navigates to the other windows, then we might not want to open the new window.

**Comment by rsolomakhin** [comment]
Maybe `Promise<WindowClient>` is referred to in in OpenWindow Algorithm 8-5: "Let client be the result of running the create window client algorithm with newContext as the argument."

IMHO, if `e.openWindow()` fails, it should reject the promise instead of returning a null. @marcoscaceres : Thoughts?

**Comment by romandev** [comment]
@rsolomakhin,

If a SW client is controlled by an active worker, we can says that the SW client is a controlled client.
(FYI, The SW client can be window client, worker and so on.)

For example, let's imagine that the origin of SW is "https://example.com".
In the SW context,
```
clients.openWindow("https://example.com/abc").then(windowClient => {
    // windowClient is controlled.
});
```

```
clients.openWindow("https://uncontrolled.com").then(windowClient => {
    // this windowClient is not controlled. So, should be null.
});
```

**Comment by rsolomakhin** [comment]
Thank you for the explanation. That makes a lot of sense. IMHO, the payment handler SW should be allowed to open only controlled clients. If a client is not controlled, then `e.openWindow()` promise should be rejected with `SecurityError`. I believe that's already in the spec, right?

**Comment by rsolomakhin** [comment]
Yep:
> If the origin of newContext is not the same as the service worker client origin associated with the payment handler, then:
>  - Reject promise with a DOMException whose name is "SecurityError".

**Comment by ianbjacobs** [comment]
@rsolomakhin or @romandev, anybody interested in a pull request in light of this thread?

Ian

**Comment by romandev** [comment]
I'll take this if you don't mind. :-)

**Comment by ianbjacobs** [comment]
I don't mind at all, thank you!

**Comment by rsolomakhin** [comment]
@romandev What changes do you plan? From what I understand, the spec is correct in omitting the `?`. The `?` in `clients.openWindow()` is used for resolving the promise with `null` in case of mismatched origin. Our behavior is different, however. If the origin is mismatched in `PaymentRequestEvent.openWindow()`, then the promise should be rejected with `SecurityError` instead. Since `PaymentRequestEvent.openWindow` does not have a possibility of resolving the promise with `null`, then the `?` should not be used. Correct?

**Comment by romandev** [comment]
@rsolomakhin 
As far as I know, your understanding is correct. 👍
So, I have a plan to remove the related sentence first from the spec.
For example, the spec says that event.[[windowClient]] can be null here. [1]
> 6. If event.[[windowClient]] is not null, then:
>> 1. If event.[[windowClient]].visibilityState is not "unloaded", reject promise with a DOMException whose name is "InvalidStateError" and abort these steps.

On the other hands, it seems to be a only case that resolves with null when newContext's origin and SW's origin are different according to the SW's spec[2].
So, my plan is that I'll re-check them again and then make a pull request.
(My co-worker @jungkees can help me as SW's spec writer.)

[1] https://w3c.github.io/payment-handler/#dfn-windowclient
[2] https://w3c.github.io/ServiceWorker/#clients-openwindow (openWindow section 6-9)

**Comment by jungkees** [comment]
Thanks @romandev for bringing me here.

I think we better reuse the clients API's [openWindow()](https://w3c.github.io/ServiceWorker/#dom-clients-openwindow) steps as much as possible. In order to do so, I can factor out the default steps to a separate algorithm that paymentRequestEvent.openWindow() can invoke with its customized hook. (See this example that we do for importScripts of HTML and service workers: https://html.spec.whatwg.org/#dom-workerglobalscope-importscripts and https://w3c.github.io/ServiceWorker/#importscripts.)

For the custom part of the steps, checking the request.[[state]] seems reasonable and easy to place in the begining of the algorithm I guess. But checking event.[[windowClient]] seems a bit too much specialized to adapt. Is checking event.[[windowClient]]'s state something inevitable?

In the importScripts's case, it was rather natural as service worker's importScripts() inherited the default implementation of WorkerGlobalScope.importScripts(). In the case of PaymentRequestEvent though, it currently defines openWindow() onto the event. I'm not sure whether we better/can just check the calling context from clients.openWindow() and if it's a paymentRequestEvent just apply the custom conditions there without adding a new method in the first place.

/cc @domenic, @annevk, @jakearchibald

**Comment by ianbjacobs** [comment]
@jungkees and @romandev, thanks for working out the details. @romandev, do you have an idea for when you might have a pull request? I'm happy to put it on the agenda of an upcoming task force call.

**Comment by ianbjacobs** [comment]
Closed via this edit:
 https://github.com/w3c/payment-handler/pull/171
