### ISSUE TITLE
Change openWindow algorithm 14.1 to 'Resolve promise with null.'

### ISSUE THREAD

**Issue by gogerald** [w3c/webpayments-payment-apps-api#201]
At this point the window is opened, so the openWindow is succeed, but because it opens a crossing origin window, so there is no WindowClient could return.

Any thoughts?

**Comment by dlongley** [comment]
It should not be a cross origin window. It should be opening a window to the same origin that the service worker is running in.

If the window opens an origin that isn't the same as the service worker's then a `"SecurityError" DOMException` is thrown ([see step 14 of the open window algorithm](https://w3c.github.io/payment-handler/#dfn-open-window-algorithm)).

**Comment by gogerald** [comment]
But that doesn't make too much sense since the window is already opened at that point. I guess this is why we return null in Clients.openWindow for service worker at the same situation. Might be good to keep them consistent to make it easier for implementation as well.

I created a pull request #202 . Feel free to comment on it.

**Comment by gogerald** [comment]
@rsolomakhin @ianbjacobs

**Comment by romandev** [comment]
Seems reasonable to me. I thought it's a little bit strange.

Even if openWindow() takes a normal origin url, it may eventually end up with a cross origin url due to server side redirection. In this case, openWindow() will reject with SecurityError as per current spec but Browser Tab(or Browser Window) is already shown to user. So, although the method is rejected, it will show about:blank or a cross origin page. (@gogerald's point)

Another case is a bit more weird. Please see the following code.
```
e.openWindow(normal_origin_url)
    .then(windowClient => {
        // openWindow is succeeded but...
        windowClient.navigate(cross_origin_url);
    });
```

Even if openWindow() is succeeded, the opened window may display a cross origin url due to windowClient.navigate() or location.href.

So, it's too difficult to block a cross origin url during openWindow especially navigation.
I think a ServiceWorker's way (resolving null) is reasonable and consistent.

**Comment by ianbjacobs** [comment]
Hi @gogerald and @romandev, is this issue closable followinfg the merge of pull request #202?

Ian

**Comment by romandev** [comment]
Sure, this is already fixed by @gogerald. I'll close this issue :)
