### ISSUE TITLE
Use payment method manifest for registration-time validation?

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-payment-apps-api#248]
@rsolomakhin,

An idea came up in a conversation today: could browsers make use of manifest information at payment handler registration time, to prevent registration of unauthorized payment handlers for URL-based payment methods?

This makes a lot of sense to me, and sounds superior to leveraging the information at matching time (during a transaction). In particular, you could alert the user to unauthorized payment apps sooner, potentially preventing them from giving credentials to malicious payment app distributors. You can't prevent that completely (because "download" is different than "register") but it might help. It would also be an opportunity for a better user experience at registration (understanding why registration fails) rather than during a transaction.

Thoughts?

Ian

**Comment by rsolomakhin** [comment]
I think that's a good idea. Can this be made optional?

**Comment by ianbjacobs** [comment]
I've not thought about this much yet but there are some nuances. For instance: if a payment app supports N payment methods and is "not authorized" for one of them, should the entire registration be scrapped, or should the payment app still be able to register for the other payment methods (either open or authorized)? 

Suppose the FooApp supports basic card and Alipay but is not authorized to support Alipay.
The merchant accepts both payment methods, so FooApp matches. FooApp controls the
user experience of selection within the handler, so the browser can't prevent the user
from *selecting* Alipay. The browser can only complain once Payment Handler API returns.

What does the browser do then? Does the browser pop up a warning to the user and relaunch
Payment Handler API?

(Also, this question seems to be relevant for "validation against payment method manifest during the transaction" as well.)

**Comment by rsolomakhin** [comment]
> if a payment app supports N payment methods and is "not authorized" for one of them, should the entire registration be scrapped, or should the payment app still be able to register for the other payment methods (either open or authorized)?

We can store the registration on disk, but warn in developer console about the payment methods that were not permitted. We can re-check the permissions at the time of payment and re-print developer console warnings at that time as well. Such behavior would benefit web developers the most, IMHO.

> Suppose the FooApp supports basic card and Alipay but is not authorized to support Alipay.
The merchant accepts both payment methods, so FooApp matches. FooApp controls the
user experience of selection within the handler, so the browser can't prevent the user
from selecting Alipay. The browser can only complain once Payment Handler API returns.

If FooApp is not authorized to handler Alipay, then the browser should not pass Alipay's payment method name into FooApp through CanMakePaymentEvent and PaymentRequestEvent. At that point, FooApp has no way of knowing whether the invoking website requested payment via Alipay. As a precaution, the browser should verify that the payment method identifier in FooApp's response is one of the authorized payment methods for FooApp. Otherwise, the browser should behave as if FooApp returned an error and print an error message to the developer console explaining what happened exactly.

**Comment by ianbjacobs** [comment]
@rsolomakhin, do you think we can close this issue as not having direct bearing on Payment Handler?

**Comment by rsolomakhin** [comment]
SGTM
