### ISSUE TITLE
Remove PaymentRequestEvent and CanMakePaymentEvent from ServiceWorker Scope?

### ISSUE THREAD

**Issue by gogerald** [w3c/webpayments-payment-apps-api#304]
I couldn't think of a good use case of exposing them to ServiceWorker scope, any ideas? 

@ianbjacobs @marcoscaceres @adrianhopebailie

**Comment by gogerald** [comment]
@romandev

**Comment by romandev** [comment]
@gogerald,

What does it means? Do you want to expose them to Window instead of SW global scope?
As you know, the events only happen in SW global scope.

**Comment by gogerald** [comment]
I mean remove 'Exposed=ServiceWorker', which indicates that the construct is exposed on 'ServiceWorker' set of interfaces, right? I don't see we have use cases that need to construct PaymentRequestEvent and CanMakePaymentEvent in service worker. Did I understand it wrong?

**Comment by gogerald** [comment]
Let me clear my opinion in a little more details, I may totally wrong though.

Payment handler (service worker) only needs to listen for PaymentRequestEvent and CanMakePaymentEvent from browser and it does not need to construct these events or we shouldn't allow it to construct. However, what I understand of 'Exposed=ServiceWorker' is about accessing constructor of these events. So removing of 'Exposed=ServiceWorker' shouldn't break the implementation, right?

**Comment by marcoscaceres** [comment]
For completeness, all events have to have a constructor. It's just a quirk of the web platform.

**Comment by romandev** [comment]
@gogerald

> I mean remove 'Exposed=ServiceWorker', which indicates that the construct is exposed on 'ServiceWorker' set of interfaces, right?

If we remove `Exposed=ServiceWorker`, we can not listen to the events in SW global scope. As far as I know, we should declare `Exposed` explicitly for all interfaces in latest web platform. In Chrome binding, if there is no `Exposed`, it is the same with `Exposed=Window`.

You might have wanted to remove constructors of those events. If so, developers would not be able to create event objects explicitly.

> I don't see we have use cases that need to construct PaymentRequestEvent and CanMakePaymentEvent in service worker. Did I understand it wrong?

Removing the constructors might be allowed in the spec perspective[1][2] but it's also important to have platform consistency where possible[3]. One use-case is so that we write tests for payment handler. We are already using it usefully[4].

[1] https://dom.spec.whatwg.org/#constructing-events
[2] https://dom.spec.whatwg.org/#defining-event-interfaces
[3] https://groups.google.com/a/chromium.org/d/msg/blink-dev/G3V0F7Rh0Io/MuLBeUZeAQAJ
[4] [Chromium test code](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/http/tests/payments/resources/payment-request-event.js?q=payment-request-event.js&dr&l=18)

**Comment by gogerald** [comment]
Thanks for details. 

Yes, I was thinking to remove constructor. It just looks not good to me to expose constructor to some one (service worker), who shouldn't use it. For test, it is better to restrict for test only or there is another way to implement.

Anyway, looks we are doing that everywhere, so I am OK with it.
