### ISSUE TITLE
Payment Handler window `.focused` field

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webpayments-payment-apps-api#307]
Proposal: when a merchant checkout window opens a payment handler window, the windows should have identical value of `.focused`. Either both are focused or both are not-focused. A payment handler window should not be able to focus itself, however.

**Comment by rsolomakhin** [comment]
Original issue reported in https://crbug.com/843920

**Comment by ianbjacobs** [comment]
Hi @rsolomakhin,

What does "when a merchant checkout window opens a payment handler window" mean? 

Ian

**Comment by rsolomakhin** [comment]
Sorry about compressing three steps into a single phrase. The following steps happen:

1. Merchant calls Payment Request.
2. User selects a Payment Handler.
3. The PaymentHandler calls `clients.openWindow()` (if I recall the API shape correctly).

**Comment by ianbjacobs** [comment]
So now, in terms of those steps, it would be my expectation that when the user selects the payment handler, if the payment handler calls openWindow() then that window would get focus. What does "A payment handler window should not be able to focus itself" mean?

Ian

**Comment by rsolomakhin** [comment]
Currently, a payment handler window is not getting focus, because it's not a regular window. A user can switch around among different open windows and tabs, which gives them focus. However, the payment handler window is glued to the merchant checkout window. So, focusing a merchant window or tab should also focus the payment handler. However, now that we discuss it more, I feel that the payment handler window should be the one with the focus instead of the merchant checkout window.

**Comment by ianbjacobs** [comment]
Here's a related question: when the sheet is shown, I take it to be a window that has focus. And then when the payment handler window open, it replaces the sheet and takes focus. I don't know whether it's the same window as the sheet or a new window.

Is is accurate to call the sheet a window that has focus? How would you describe the shift of focus from that window to the payment handler's window (if any)?

Thanks for talking through this,

Ian

**Comment by rsolomakhin** [comment]
Our payment sheets are native dialogs without any HTML, so it would not be accurate to call them a window.

**Comment by ianbjacobs** [comment]
Since there might be different ways to implement this, I don't want to be overly specific about the relationships among:

 - Merchant window
 - Sheet
 - Payment handler window (if any)

It does seem reasonable to say that the focus shifts to the PH window with clients.openWindow().

What if you click on another tab at that time? It seems reasonable to leave the PH window open and change contexts, but to be able to return to the merchant tab and resume focus on the payment handler. Does that sound right?

Ian

**Comment by rsolomakhin** [comment]
Sounds right :+1:

**Comment by ianbjacobs** [comment]
+1 to when the payment handler calls e.openWindow(), the payment handler window should take over focus from merchant checkout window.

**Comment by ianbjacobs** [comment]
@romandev, do you agree with the proposal that when the payment handler calls e.openWindow(), the payment handler window should take over focus from merchant checkout window?

**Comment by adrianhopebailie** [comment]
There is a security concern that I discussed recently with @marcoscaceres regarding openWindow that may be relevant here.

It is important that, even though the PH window is "special", it doesn't appear so the user. i.e. They should never be led to believe that somehow the PH window is privileged or worse, native browser chrome.

A suggestion was that the PH window should open a new window exactly the way clicking a `<a target="_blank">` element would do.

I agree that this window would then have focus.

The question I see in this issue is whether or not the merchant window's `.focused` property is also still `true`.

My suggestion would be that when the payment sheet appears that the merchant window is no longer in focus, i.e. `.focused === false` (maybe even blurred or overlaid with a 50% opacity mask) and is somehow locked down to prevent it showing anything new "around" the payment sheet that may somehow mislead users.

If the user invokes a PH that calls `openWindow()` this opens a new window and the user interacts with this window. The window should also be locked down to prevent the user navigating away from the PH (address bar frozen, back/forward disabled) within that window.

If the user switches back to the merchant window they should only be able to interact with the payment sheet which is still overlaid over the website and they should have only a single available button/element they can invoke and that is a `Cancel` that will cause the PR promise to reject or return the user to the payment sheet to pick another payment instrument.

Clicking cancel should also kill the PH window and raise an abort event on the PH service worker.

I am a little behind on the current implementation, so apologies if this is already there, but keen to hear thoughts on this to address some of Mozillas security concerns.

**Comment by rsolomakhin** [comment]
Sounds good, @adrianhopebailie. This is pretty much the implementation we have in Chrome, except for the `focused` field changes, but that's a bug on our part that we will fix.

**Comment by ianbjacobs** [comment]
Closing because there is consensus and it is subsumed by 
https://github.com/w3c/payment-handler/issues/321
