### ISSUE TITLE
Clarification on Payment App "Options"

### ISSUE THREAD

**Issue by zkoch** [w3c/webpayments-payment-apps-api#90]
In the [registration example](https://w3c.github.io/webpayments-payment-apps-api/#register-example), I see there is a mechanism to explicitly list (and "name") available payment options within the payment app. Is it assumed that the UA will show all of those options that match? I'm unclear from reading the spec (sorry if I missed it)?

**Comment by zkoch** [comment]
Ah, now I see in [9.2](https://w3c.github.io/webpayments-payment-apps-api/#matching-payment-apps) this bit:

> The user agent must enable the user to select any matching payment app options.

If this means we *must* show, for example, "Visa ending ****4756" inside of our UI, I would be strongly opposed to this.

**Comment by ianbjacobs** [comment]
See 4.6:

The user agent may offer features to facilitate selection. For example, instead of merely displaying information about a payment app that supports cards, the user agent could display some representation of individual cards stored in the payment app. If the user can select an option directly, that could contribute to reducing the total number of required user actions. User agents might also enable the user to optimize payments using certain payment apps on certain Web sites. User experience optimizations such as these lie outside the scope of this specification.

9.2 is not meant to require display of options. It's meant to say "If you are doing options and they match, then the user should be able to select the matching ones."

**Comment by ianbjacobs** [comment]
We discussed this on the 9 Feb call:
 http://www.w3.org/2017/02/09-wpwg-minutes.html

Some notes in particular:

 * There was consensus that we should not require UAs to display option information provided by the payment app. (That is: "MAY" or "SHOULD" rather than "MUST").
 * It was pointed out that the UX that is best for mobile may be different for desktop, and therefore we should continue to discuss in the task force API support for providing the information to the user agent.
 * We asked about the experience so far in native, and from Google we heard that they are only providing app-level presentation on mobile. We are also asking other implementers for their experience.

Ian

**Comment by ianbjacobs** [comment]
I am closing this issue in favor of issue #98, which I believe more comprehensively addresses the topic of how much granularity / how many levels we want to be able to expression.

I will carry to that issue the consensus point that if we provide options to the UA, the UA should not be required to display them.
